### ISSUE TITLE
Unable to use a ${opt:stage} as a bucket name

### ISSUE THREAD

**Issue by komw** [sbstjn/serverless-s3bucket-sync#4]
Is in title. It is unable to use a stage name variable in bucket name

**Comment by sbstjn** [comment]
Your configuration looks like this, right?

```
custom:
  s3-sync:
    - folder: relative/folder
      bucket: ${opt:stage}-bucket-name
```

I don't know if/when serverless will transform the variables into the corresponding values. Maybe there is function that can be used to translate the string with variables into the final values. Currently I have no clue how to handle this :(

**Comment by komw** [comment]
Yes, and it doesn't work, so using a stages is useless because you can't separate some static files.
Please look at serverless-sync-s3buckets plugin. There is a full support of serverless variables in configuration.

**Comment by tmaslen** [comment]
I used `${self:provider.stage}` and it worked...

```
provider:
  stage: ${opt:stage,'dev'}
custom:
  s3-sync:
    - folder: static
      bucket: ${self:provider.stage}.mywebsite.com
```

Called it like so...

```
sls sync --stage test
```
